### ISSUE TITLE
Domain list syntax

### ISSUE THREAD

**Issue by yislennierm** [dfirsec/check_rep#4]
Hi! Awesome job! 

I'm trying to use a domain lists and can not make it work, is it there any particular syntax we need to use? 

tried 
python3 check_rep.py  --mx domains.txt  
python3 check_rep.py  --mx FILE domains.txt  

but gets
usage: check_rep.py [-h] [--log] [--vt] [--fg | --mx FILE [FILE ...]] query
check_rep.py: error: the following arguments are required: query

the file domains.txt is a list of domain names 
Example:
www.bielsko-biala.aq2e.com
www.bierzacefakty24.epizy.com
www.bierzemy-udzialy.eu
www.big-data-server.com
www.bigboytruks.com
www.bigcappower.com
www.bigdesign.top
www.bigmarketplace.ng
www.bignamestanfree.wixsite.com
www.bigsecureeu.com
www.bigsklep.com
www.bigstart-i.info
www.bigswipes.com
www.bigthinkingbusiness.com
www.biik.cc

best regards

**Comment by yislennierm** [comment]
never mind found the way, ;-)

**Comment by dfirsec** [comment]
Hi, thanks for pointing that out.  I must have made a change that inadvertently caused an error with the optional arguments.  I'll correct it and push out the update shortly.

**Comment by dfirsec** [comment]
Issue resolved, please update and let me know if you experience any issues.  Thanks again.
